backend:
  replicaCount: 2
  image:
    repository: ashh501/three-tier-backend
    tag: 8e76654a95e0a71bb8b35c9c63f03a335087e09b
    pullPolicy: Always

frontend:
  replicaCount: 1
  image:
    repository: ashh501/three-tier-frontend
    tag: e1c8838343e71804bb1ce8f4981ab082a6e964d0
    pullPolicy: Always

backendService:
  type: ClusterIP
  port: 5000

frontendService:
  type: NodePort
  port: 80
