backend:
  replicaCount: 2
  image:
    repository: ashh501/three-tier-backend
    tag: 268ee89178cb297c72355bc2ab760b1d4f9c8732
    pullPolicy: Always

frontend:
  replicaCount: 1
  image:
    repository: ashh501/three-tier-frontend
    tag: e1c8838343e71804bb1ce8f4981ab082a6e964d0
    pullPolicy: Always

backendService:
  type: ClusterIP
  port: 5000

frontendService:
  type: NodePort
  port: 80
