backend:
  replicaCount: 2
  image:
    repository: ashh501/three-tier-backend
    tag: c06562afe8414ba0c8b6834adecb27a7ae40fb9d
    pullPolicy: Always

frontend:
  replicaCount: 1
  image:
    repository: three-tier-frontend
    tag: v2
    pullPolicy: Never

backendService:
  type: ClusterIP
  port: 5000

frontendService:
  type: NodePort
  port: 80
