apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ashh501/three-tier-backend:f5935f8e923f1b1497be8ef0fcaa61f2abc821b6
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_PASSWORD
              value: "postgres123"
